In [17]:
# prepare datasets
import pandas as pd
import numpy as np

data_file = pd.read_csv("breast-cancer.data", usecols=[1, 2, 3, 4, 5, 6, 7, 8, 9])
data = data_file.values
target_file = pd.read_csv("breast-cancer.data", usecols=[0])
t = target_file.values
target = []
for i in range(0, 285):
    if(data[i][0] == '10-19'):
        data[i][0] = 1
    if(data[i][0] == '20-29'):
        data[i][0] = 2
    if(data[i][0] == '30-39'):
        data[i][0] = 3
    if(data[i][0] == '40-49'):
        data[i][0] = 4
    if(data[i][0] == '50-59'):
        data[i][0] = 5
    if(data[i][0] == '60-69'):
        data[i][0] = 6
    if(data[i][0] == '70-79'):
        data[i][0] = 7
    if(data[i][0] == '80-89'):
        data[i][0] = 8
    if(data[i][0] == '90-99'):
        data[i][0] = 9
    if(data[i][1] == 'lt40'):
        data[i][1] = 1
    if(data[i][1] == 'ge40'):
        data[i][1] = 2
    if(data[i][1] == 'premeno'):
        data[i][1] = 3
    if(data[i][2] == '0-4'):
        data[i][2] = 1
    if(data[i][2] == '5-9'):
        data[i][2] = 2
    if(data[i][2] == '10-14'):
        data[i][2] = 3
    if(data[i][2] == '15-19'):
        data[i][2] = 4
    if(data[i][2] == '20-24'):
        data[i][2] = 5
    if(data[i][2] == '25-29'):
        data[i][2] = 6
    if(data[i][2] == '30-34'):
        data[i][2] = 7
    if(data[i][2] == '35-39'):
        data[i][2] = 8
    if(data[i][2] == '40-44'):
        data[i][2] = 9
    if(data[i][2] == '45-49'):
        data[i][2] = 10
    if(data[i][2] == '50-54'):
        data[i][2] = 11
    if(data[i][2] == '55-59'):
        data[i][2] = 12
    if(data[i][3] == '0-2'):
        data[i][3] = 1
    if(data[i][3] == '3-5'):
        data[i][3] = 2
    if(data[i][3] == '6-8'):
        data[i][3] = 3
    if(data[i][3] == '9-11'):
        data[i][3] = 4
    if(data[i][3] == '12-14'):
        data[i][3] = 5
    if(data[i][3] == '15-17'):
        data[i][3] = 6
    if(data[i][3] == '18-20'):
        data[i][3] = 7
    if(data[i][3] == '21-23'):
        data[i][3] = 8
    if(data[i][3] == '24-26'):
        data[i][3] = 9
    if(data[i][3] == '28-30'):
        data[i][3] = 10
    if(data[i][3] == '31-33'):
        data[i][3] = 11
    if(data[i][3] == '34-36'):
        data[i][3] = 12
    if(data[i][3] == '37-39'):
        data[i][3] = 13
    if(data[i][4] == 'yes'):
        data[i][4] = 1
    if(data[i][4] == 'no'):
        data[i][4] = 2
    if(data[i][4] == '?'):
        data[i][4] = 3
    if(data[i][6] == 'left'):
        data[i][6] = 1
    if(data[i][6] == 'right'):
        data[i][6] = 2
    if(data[i][7] == 'left_up'):
        data[i][7] = 1
    if(data[i][7] == 'left_low'):
        data[i][7] = 2
    if(data[i][7] == 'right_up'):
        data[i][7] = 3
    if(data[i][7] == 'right_low'):
        data[i][7] = 4
    if(data[i][7] == 'central'):
        data[i][7] = 5
    if(data[i][7] == '?'):
        data[i][7] = 6
    if(data[i][8] == 'yes'):
        data[i][8] = 1
    if(data[i][8] == 'no'):
        data[i][8] = 2
    if t[i][0] == 'no-recurrence-events':
        target.append(1)
    if t[i][0] == 'recurrence-events':
        target.append(2)
    
print(data)
target = np.array(target)
print(target)

[[4 3 5 ... 2 3 2]
 [4 3 5 ... 1 2 2]
 [6 2 4 ... 2 1 2]
 ...
 [6 2 5 ... 2 1 2]
 [4 2 7 ... 1 2 2]
 [5 2 7 ... 1 2 2]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [18]:
# knn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score, precision_score

# run model
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=0)
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

#evaluation
print('Accuracy:')
print(np.mean(y_pred == y_test))
print('Recall:')
print(recall_score(y_test, y_pred, average='macro'))
print('Precision:')
print(precision_score(y_test, y_pred, average='macro'))

Accuracy:
0.6666666666666666
Recall:
0.5635451505016723
Precision:
0.6484375


In [19]:
# Decision tree
from sklearn.tree import DecisionTreeClassifier

# run model
tree = DecisionTreeClassifier(random_state=0)
tree.fit(X_train, y_train)
y_pred = tree.predict(X_test)

#evaluation
print('Accuracy:')
print(np.mean(y_pred == y_test))
print('Recall:')
print(recall_score(y_test, y_pred, average='macro'))
print('Precision:')
print(precision_score(y_test, y_pred, average='macro'))

Accuracy:
0.6388888888888888
Recall:
0.5752508361204014
Precision:
0.5925925925925926


In [20]:
# random forest
from sklearn.ensemble import RandomForestClassifier

# run model
forest = RandomForestClassifier(n_estimators=100, random_state=0)
forest.fit(X_train, y_train)
y_pred = forest.predict(X_test)

# evaluation
print('Accuracy:')
print(np.mean(y_pred == y_test))
print('Recall:')
print(recall_score(y_test, y_pred, average='macro'))
print('Precision:')
print(precision_score(y_test, y_pred, average='macro'))

Accuracy:
0.6805555555555556
Recall:
0.6162207357859532
Precision:
0.6486631016042781


In [21]:
# SVM
from sklearn.svm import SVC
min_on_training = X_train.min(axis=0)
range_on_training = (X_train - min_on_training).max(axis=0)
X_train_scaled = (X_train - min_on_training) / range_on_training
X_test_scaled = (X_test - min_on_training) / range_on_training
svc = SVC(kernel='linear', C=1000)
svc.fit(X_train_scaled, y_train)
y_pred = svc.predict(X_test_scaled)

# evaluation
print('#Linear')
print('Accuracy:')
print(np.mean(y_pred == y_test))
print('Recall:')
print(recall_score(y_test, y_pred, average='macro'))
print('Precision:')
print(precision_score(y_test, y_pred, average='macro'))

svc = SVC(kernel='poly', C=1000)
svc.fit(X_train_scaled, y_train)
y_pred = svc.predict(X_test_scaled)

# evaluation
print('#Poly')
print('Accuracy:')
print(np.mean(y_pred == y_test))
print('Recall:')
print(recall_score(y_test, y_pred, average='macro'))
print('Precision:')
print(precision_score(y_test, y_pred, average='macro'))

svc = SVC(kernel='rbf', C=1000)
svc.fit(X_train_scaled, y_train)
y_pred = svc.predict(X_test_scaled)

# evaluation
print('#Rbf')
print('Accuracy:')
print(np.mean(y_pred == y_test))
print('Recall:')
print(recall_score(y_test, y_pred, average='macro'))
print('Precision:')
print(precision_score(y_test, y_pred, average='macro'))

#Linear
Accuracy:
0.6805555555555556
Recall:
0.5911371237458194
Precision:
0.6624441132637854
#Poly
Accuracy:
0.6805555555555556
Recall:
0.6162207357859532
Precision:
0.6486631016042781
#Rbf
Accuracy:
0.7083333333333334
Recall:
0.6463210702341137
Precision:
0.6871657754010696
